### ISSUE TITLE
Add Github Action Integration guides to Kobiton Docs

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#222]
Tasks:

- Refer to the existing structure of our Integration section (CircleCI example): https://docs.kobiton.com/integrations/circleci/
- Add 2 pages, each page introduce briefly about the feature of the Github Action of Kobiton and link to the marketplace for how to use them.
  - Upload an app to Kobiton: https://github.com/marketplace/actions/kobiton-upload-mobile-app
  - Run Appium Script on Kobiton devices: https://github.com/marketplace/actions/kobiton-execute-appium-test
 
It is highly recommended that you try to follow the docs yourself and verify if the steps in the guides are still up to date. If you run into any issue, please contact me.

**Comment by tungmhoang** [comment]
This is lower priority than this: https://github.com/kobiton/docs/issues/223

**Comment by Hikkigaya** [comment]
@tungmhoang I'm run into an issue with the version number. It seems that the details for defining it are missing in the document
![Uploading 107.PNG…]()

**Comment by Hikkigaya** [comment]
@tungmhoang 
![107](https://github.com/kobiton/docs/assets/20087517/1e41c356-8076-4043-b446-9328971e3c71)

**Comment by tungmhoang** [comment]
@Hikkigaya the version is v1.0.0 as indicates in the marketplace link.
**Important**: I have updated the description of the tasks. I decided it's better to just link our docs page to the marketplace site to avoid maintaining two different sites for the same guide.

**Comment by Hikkigaya** [comment]
@tungmhoang thank you for the clarification, I was a bit confused there.

I think I'm good with GitHub actions, but setting up a repository that builds an apk, downloading and installing all the packages for the build to run, and configuring an entire Android project for that, is a little above my technical expertise, especially since android or apks are involved.

Should I migrate the page, since the workflow file actually ran accurately as it should? 

Or should I spend some more time setting up an Android project and creating a build to upload?

**Comment by Hikkigaya** [comment]
@tungmhoang NVM.

Used the Zoom apk as a test, it worked. the app was uploaded to Kobiton via Github Action successfully!

**Comment by Hikkigaya** [comment]
@tungmhoang I just tried to access the app on Kobiton and I got this error in the Kobiton Portal, is this because I used a ready made APK, or something else?
![108](https://github.com/kobiton/docs/assets/20087517/9eeaeb4e-33c9-4aab-8b92-7992cc460c40)

**Comment by tungmhoang** [comment]
@Hikkigaya 
It's alright, as long as you can upload the app it is fine.
Let's focus on linking the 2 mentioned pages in our docs to the github marketplace first (no need to migrate content).
