### ISSUE TITLE
Add new page "Add iOS devices" to PR 190

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#224]
Tasks:

- Check out the PR: https://github.com/kobiton/docs/pull/190
- Add a new page under docs/modules/device-lab-management/pages/ios-devices/. Fill in the new page with this content:
[KOBITON-Add iOS devices-300524-091231.pdf](https://github.com/kobiton/docs/files/15496606/KOBITON-Add.iOS.devices-300524-091231.pdf)
- At the start of the pdf file there is a link to the prepare an iOS device page. Link that to our new page at docs/modules/device-lab-management/pages/android-devices/prepare-ios-device.adoc
- If there are links that points to current page on docs.kobiton.com, use xref to reference accordingly.

**Comment by Hikkigaya** [comment]
@tungmhoang task completed and pushed to the repository.
