### ISSUE TITLE
Add iOS image injection SDK and image injection automation guide

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#230]
Tasks:
- Create a new branch from `main`
- Add 2 new pages
  - "Add the image injection SDK to your iOS app" under Apps/Enable image injection
  - "Create an image injection script" under Automation testing/Scripting
Migrate the content of this file 
[Kobiton SDK User Guide.docx](https://github.com/user-attachments/files/15789515/Kobiton.SDK.User.Guide.docx)
, which includes instructions for both of the above, into the appropriate place.

**Comment by erincbailey** [comment]
@Hikkigaya 
We also need to update the "Use image injection" page in Manual testing: https://docs.kobiton.com/manual-testing/test-your-app-camera
Throughout this task - please make sure we are consistent in the wording with how we describe the Android SDK image injection - https://docs.kobiton.com/apps/image-injection-sdk/add-the-sdk-to-your-android-app
