### ISSUE TITLE
Add user guide to enable Jira Data Center integration

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#234]
Tasks:
- Check out a new branch
- Create a new page under Integrations/Jira. Fill in the content of this pdf 
[KOBITON-Enable Jira Data Center integration-130624-084410.pdf](https://github.com/user-attachments/files/15816575/KOBITON-Enable.Jira.Data.Center.integration-130624-084410.pdf).
- Revise the style and wordings.
- Make sure images is not over 100KB in size.

**Comment by Hikkigaya** [comment]
Task complete, pull request created.
