### ISSUE TITLE
Add disable Google Play Protect in prepare android devices

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#236]
Tasks:
- Checkout a new branch
- Update the file `device-lab-management/android-devices/prepare-android-device` page.
- Add a section called "Turn off Google Play Protect (optional)"
- Add the below steps to that section: 
![Screenshot 2024-06-17 at 10 24 14 AM](https://github.com/kobiton/docs/assets/119557676/276633fa-e470-4dd1-9c25-00307214c505)

**Comment by Hikkigaya** [comment]
Task completed, PR created.
