### ISSUE TITLE
Add release notes 4.13.2S

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#247]
Tasks:
- Checkout a new branch
- Migrate this doc to a new page under release-notes, following the release notes naming convention. 
[KOBITON-v4.13.2S July 21, 2024-030724-084540.pdf](https://github.com/user-attachments/files/16081057/KOBITON-v4.13.2S.July.21.2024-030724-084540.pdf)

- Review the style of the docs to make sure it is consistent with the style of our docs site.
- Run the docs through Grammarly or ChatGPT to correct grammar mistakes and typos.
- Replace any links that point to pages on docs.kobiton.com to the correct internal reference.

**Comment by Hikkigaya** [comment]
Release notes migrated and pull request created.
