### ISSUE TITLE
Migrate Test Management v2 docs

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#287]
Migrate Test Management v2 docs to docs site.
 
Tasks:

- Check out the `main` branch
- Under `test-management`, create these new folder: `test-case`, `test-suite`, `test-run`
- Under `test-suite`, migrate the attached pdf file to a page called `Create and manage test suites`: 
[KOBITON-Create and manage test suites [Review]-121124-100049.pdf](https://github.com/user-attachments/files/17714651/KOBITON-Create.and.manage.test.suites.Review.-121124-100049.pdf)

**Comment by Hikkigaya** [comment]
@tungmhoang I've created the 3 folders and have added them them to the nav files.

Two folders are currently empty so the nav link does go anywhere for them.

The third folder `test-suite` now contains a content of the PDF attached.

I'm waiting for the the last three images which were missing from the PDF. 

Will push the change ... directly to main?... when the images are provided and added.
