### ISSUE TITLE
Migate Resolve a Blocker document

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#292]
Tasks:
- Check out the #288 PR
- Add the following pdf file, replacing the current content in the file `docs/modules/test-management/pages/remediation/element-selection-remediation.adoc` with the following pdf (including title): 
[KOBITON-Resolve a blocker [Ready for Review]-151124-114709.pdf](https://github.com/user-attachments/files/17775127/KOBITON-Resolve.a.blocker.Ready.for.Review.-151124-114709.pdf)
- Make sure all images are left-justified, under 100KB, and have alt text.

**Comment by Hikkigaya** [comment]
Changes have been pushed to PR: https://github.com/kobiton/docs/pull/288
