### ISSUE TITLE
Migrate Create and Manage a Test Run

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#294]
Tasks:
- Check out the https://github.com/kobiton/docs/pull/288 PR
- Create a new folder `test-run` under `docs/modules/test-management/pages`
- Add this file under the new `test-run` folder: 
[KOBITON-Create and manage a test run [Review]-181124-070229.pdf](https://github.com/user-attachments/files/17796211/KOBITON-Create.and.manage.a.test.run.Review.-181124-070229.pdf)
- Make sure all images are left-justified, under 100KB, and have alt text.
- Make sure all navigation to the new file is valid.

**Comment by Hikkigaya** [comment]
@tungmhoang I think there is some content missing in the file, let me know that is the case. Kindly send another file if that is the case.
![53](https://github.com/user-attachments/assets/44b943ce-5e95-43b1-8e21-d5e15b87f60c)

**Comment by Hikkigaya** [comment]
@tungmhoang assuming that the file was complete. This task has been completed and the changes have been pushed to the PR.
