### ISSUE TITLE
Migrate Revew Test Run Results

### ISSUE THREAD

**Issue by tungmhoang** [kobiton/docs#295]
Tasks:
- Check out the https://github.com/kobiton/docs/pull/288 PR
- Add this page under `docs/modules/test-management/pages/test-run`: 
- Make sure all images are left-justified, under 100KB, and have alt text.
[KOBITON-Review test run results [Review]-181124-085457.pdf](https://github.com/user-attachments/files/17797493/KOBITON-Review.test.run.results.Review.-181124-085457.pdf)

- Make sure all navigation to the new file is valid.

**Comment by Hikkigaya** [comment]
@tungmhoang here as well, I think there is some content missing in the file, let me know that is the case. Kindly send another file if that is the case.
![54](https://github.com/user-attachments/assets/5e0899d2-e676-4078-b4cb-a211d76d263d)

**Comment by Hikkigaya** [comment]
This task has been completed and changes pushed to PR
